### ISSUE TITLE
Love the theme! 💖💖

### ISSUE THREAD

**Issue by tejasag** [lubna/lubnadev-vscode-theme#1]
Hey! Just scrolling through trending extensions on visual studio code, I came across lubnadev-theme. Being one who is very picky with his IDE themes, this theme immediately caught my eye and became my personal favorite because of the awesome color combinations and perfect use of them at right places. Just wanted to say thank you for making this theme and helping people like me have better coding experience. 
(btw would also love to see a jetbrains version of it 😜but no pressure )

\- Tejas

**Comment by lubna** [comment]
Thanks. I'm going to close this since it isn't an issue but I'm glad you're enjoying the theme. Maybe you can add this as a review on the VS Code marketplace though.
